<?php
// public/history.php
session_start();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Playlists - Sonoresu</title>
    <link rel="stylesheet" href="global.css">
    <style>
        .history-layout {
            display: grid;
            grid-template-columns: 250px 1fr;
            gap: 40px;
        }
        /* Profile Record Avatar */
        .profile-avatar {
            width: 250px; height: 250px;
            background: #666;
            border-radius: 50%;
            position: relative;
        }
        .profile-avatar::before {
            content: '💿';
            position: absolute; top: 10px; left: 10px;
            font-size: 3rem; background: #000; border-radius: 50%;
            border: 4px solid var(--text-light);
        }
        
        /* Playlist List */
        .playlist-header-card {
            background-color: var(--card-bg);
            border-radius: var(--radius-card);
            padding: 20px; margin-bottom: 30px;
        }
        .action-icons { display: flex; gap: 10px; float: right; font-size: 1.5rem; }
        
        .list-stack { display: flex; flex-direction: column; gap: 15px; }
        .list-item {
            background-color: var(--card-bg);
            border-radius: var(--radius-pill);
            padding: 15px 30px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            color: var(--text-light);
        }
        .list-item .item-info { display: flex; align-items: center; gap: 15px; }
        .list-item .circle { width: 40px; height: 40px; background: #555; border-radius: 50%; }
        .play-btn { font-size: 1.5rem; cursor: pointer; }
        
        @media (max-width: 768px) { .history-layout { grid-template-columns: 1fr; } }
    </style>
</head>
<body>
    <header class="main-header wireframe-bg">
        <h1>What's our mood for today?</h1>
        <div class="mood-form">
            <input type="text" class="mood-input" placeholder="✨ e.g. morning dawn sipping coffee">
        </div>
        <p class="sub-text">feeling something new? ✌️</p>
        <nav class="nav-tabs">
            <a href="home.php" class="nav-tab">Home</a>
            <a href="history.php" class="nav-tab active">Your Playlists</a>
            <a href="lounge.php" class="nav-tab">Global lounge</a>
        </nav>
    </header>

    <div class="container history-layout">
        <aside>
            <div class="profile-avatar"></div>
        </aside>
        <main>
            <div class="playlist-header-card">
                <div class="action-icons">
                    <span title="Add">➕</span> <span title="Music">🎵</span> <span title="Share">↗️</span>
                </div>
                <h2 class="text-white" style="margin-bottom:10px;">Your Mood Capsules</h2>
                <small class="text-muted" style="float:right;">date made: 00/00/0000</small>
                <p class="text-muted">Prompt history details generated by Gemini will be displayed here as a description.</p>
            </div>
            
            <div class="list-stack">
                <?php for($i=1; $i<=6; $i++): ?>
                <div class="list-item">
                    <div class="item-info">
                        <div class="circle"></div>
                        <div>
                            <strong>lorem ipsum <?php echo $i; ?></strong><br>
                            <small class="text-muted">lorem ipsum</small>
                        </div>
                    </div>
                    <span class="play-btn">▶</span>
                </div>
                <?php endfor; ?>
            </div>
        </main>
    </div>
</body>
</html>